
parameters:

services:
    _defaults:
        autowire: true   
        autoconfigure: true 
    App\:
        resource: '../src/'

    App\Service\SecurityService:
        arguments:
            $clock: '@clock'
            $jwtSecret: '%env(JWT_SECRET)%'
            $jwtExpiration: '%env(int:JWT_EXPIRATION)%'
