
parameters:

services:
    _defaults:
        autowire: true   
        autoconfigure: true 
    App\:
        resource: '../src/'
    Psr\Clock\ClockInterface: '@clock'
    clock:
        class: Lcobucci\Clock\SystemClock
        arguments:
            $timezone: 'UTC'

    App\Service\SecurityService:
        arguments:
            $clock: '@clock'
            $jwtSecret: '%env(JWT_SECRET)%'
            $jwtExpiration: '%env(int:JWT_EXPIRATION)%'
